### ISSUE TITLE
Knight move as first move of the game invalid (introduced bug)

### ISSUE THREAD

**Issue by brane-games** [Geras1mleo/Chess#24]
Hi Sviatoslav! This used to work, but became a problem when I pulled in the latest changes.

**Describe the bug**
This test fails.
```
    [Fact]
    public void Knight_As_First_Move_Works()
    {
        var board = ChessBoard.LoadFromFen("rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1");
        var success = board.Move("b1c3");

        Assert.True(success);
    }
```
I've found the commit that introduced this: https://github.com/Geras1mleo/Chess/commit/7da08503396410d38e607fa9743efa60ac7ddf35

**To Reproduce**
Try a knight move as first move.

**Expected behaviour**
It is a valid move.

**Screenshots**
-nope

**Additional context**
The changes in SanBuilder.cs introduced this.

**Comment by Geras1mleo** [comment]
Hi @brane-games 

Sooo, the reason this is not working is because of [SAN (Notation of move)](https://en.wikipedia.org/wiki/Algebraic_notation_(chess)#Notation_for_moves):

> **Notation for moves**
> 
> In standard (or short form) algebraic notation, each move of a piece is indicated by the piece's uppercase letter, plus the
> coordinates of the destination square. For example, Be5 (bishop moves to e5), Nf3 (knight moves to f3). For pawn moves, a 
> letter indicating pawn is not used, only the destination square is given. For example, c5 (pawn moves to c5). 

Parser thinks you are moving some _"pawn"_ from b1 to c3...

When you use: `board.Move("Nb1c3");` with the **N** the parser uses knight and sees it on given position.

I made it stricter to keep in line with other SAN parsers and to be consistent with the protocol.

Actually this issue is now a part of [this](https://github.com/Geras1mleo/Chess/issues/4) issue of yours where I promised to implement those features but still didn't have time to do it 😣

If you have any further questions, please contact me!

Greetings Sviatoslav

**Comment by brane-games** [comment]
Oh, so it's kind of expected. No problem, thanks for the explanation!
